import "@/styles/globals.css"
import { Inter } from "next/font/google"
import { cookies } from "next/headers"
import Provider from "./Provider"
// import { ThemeProvider, createTheme } from "@mui/material"

type RootProps = {
  children: React.ReactNode
}

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

// material ui theme
// const theme = createTheme({
//   palette: {
//     primary: {
//       main: "#00B4BD"
//     }
//   }
// })

export default function RootLayout({ children }: RootProps) {
  const cookieStore = cookies()
  const token = cookieStore.get("token")
  // TODO: validate token if needed

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ThemeProvider theme={theme}> */}
        <Provider isAuthenticated={token !== undefined && token.toString() !== ""}>{children}</Provider>
        {/* </ThemeProvider> */}
      </body>
    </html>
  )
}
