import "@/styles/globals.css"
import { Inter } from "next/font/google"

type RootProps = {
  children: React.ReactNode,
}

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({ children }: RootProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
